services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
      target: ${DOCKER_TARGET:-dev}
    ports:
      - "${PHOENIX_PORT:-4000}:4000"
    env_file:
      - .env
    environment:
      - MIX_ENV=${MIX_ENV:-dev}
      - DATABASE_URL=ecto://postgres:postgres@postgres:5432/app_${MIX_ENV:-dev}
      - PHX_IP=0.0.0.0
      - PORT=4000
    volumes:
      - ./app:/app
      - /app/deps
      - /app/_build
    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "mix setup && mix phx.server"]
    restart: ${RESTART_POLICY:-no}

volumes:
  postgres_data: