services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: app_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./app
      target: runtime
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - MIX_ENV=prod
      - DATABASE_URL=ecto://postgres:${POSTGRES_PASSWORD}@postgres:5432/app_prod
      - PORT=4000
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_prod_data: