import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :app, AppWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Production fire incident configuration (standard 24-hour timeouts)
config :app,
  incident_cleanup_threshold_hours: 24,  # 24 hours standard
  fire_clustering_expiry_hours: 24       # 24 hours standard

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
