name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: |
        docker build -f app/Dockerfile -t fireapp:test --target build app/
    
    - name: Start services
      run: |
        docker-compose up -d postgres
        sleep 10
    
    - name: Run tests
      run: |
        docker run --rm \
          --network container:$(docker-compose ps -q postgres) \
          -e MIX_ENV=test \
          -e DATABASE_URL=ecto://postgres:postgres@localhost:5432/app_test \
          fireapp:test \
          sh -c "mix deps.get && mix ecto.create && mix ecto.migrate && mix test"
    
    - name: Check compilation
      run: |
        docker run --rm fireapp:test mix compile --warnings-as-errors
    
    - name: Stop services
      run: docker-compose down

  build-production:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build production image
      run: |
        docker build -f app/Dockerfile -t fireapp:prod --target runtime app/
    
    - name: Test production build
      run: |
        docker run --rm fireapp:prod ./bin/app version