name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create test environment file
        run: |
          cp .env.example .env
          echo "SECRET_KEY_BASE=$(openssl rand -base64 48)" >> .env

      - name: Start services
        run: |
          docker compose up -d
          sleep 15

      - name: Run tests
        run: |
          docker compose run --rm -e MIX_ENV=test app mix test

      - name: Check compilation warnings
        run: |
          docker compose run --rm app mix compile --warnings-as-errors

      - name: Run code analysis
        run: |
          docker compose run --rm app mix format --check-formatted

      - name: Stop services
        run: docker compose down
